<?php
%A%Nepada\Bridges\TexyLatte\TexyModeMacro::validateTemplate($template);
%A%ob_start(%a?%) ?>TYPO: ... example@example.com, http://example.com<?php%A?%%s%echo %a%->texyTypo%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>LINE: ... example@example.com, http://example.com <p>paragraph</p><?php%A?%%s%echo %a%->texyLine%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>BLOCK:
... example@example.com, http://example.com <p>paragraph</p>

Paragraph
<?php%A?%%s%echo %a%->texy%a%ob_get_clean()) ?>

<?php%A?%%s%$_texyModeStack[] = $_texy->getMode();%A%$_texy->setMode("custom");%A%ob_start(%a?%) ?>%A?%TYPO: ... example@example.com, http://example.com<?php%A?%%s%echo %a%->texyTypo%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>LINE: ... example@example.com, http://example.com <p>paragraph</p><?php%A?%%s%echo %a%->texyLine%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>BLOCK:
... example@example.com, http://example.com <p>paragraph</p>

Paragraph
<?php%A?%%s%echo %a%->texy%a%ob_get_clean()) ?>

<?php%A?%%s%$_texyModeStack[] = $_texy->getMode();%A%$_texy->setMode("default");%A%ob_start(%a?%) ?>%A?%TYPO: ... example@example.com, http://example.com<?php%A?%%s%echo %a%->texyTypo%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>LINE: ... example@example.com, http://example.com <p>paragraph</p><?php%A?%%s%echo %a%->texyLine%a%ob_get_clean()) ?>

<?php%A?%%s%ob_start(%a?%) ?>BLOCK:
... example@example.com, http://example.com <p>paragraph</p>

Paragraph
<?php%A?%%s%echo %a%->texy%a%ob_get_clean()) ?>

<?php%A?%%s%$_texy->setMode(array_pop($_texyModeStack));%A%$_texy->setMode(array_pop($_texyModeStack));%A%