<?php
%A%source: %a%Bridges/fixtures/filters.default-mode.latte%a%
%A%
%a%echo LR\HtmlHelpers::escapeText(($this->filters->texyTypo)($textTypo))%a%
%A?%
%a%echo LR\HtmlHelpers::escapeText(($this->filters->texyLine)($textLine))%a%
%A?%
%a%echo LR\HtmlHelpers::escapeText(($this->filters->texy)($textBlock))%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo LR\HtmlHelpers::escapeText($textTypo)%a%
%A%
%s%echo%a%filterContent('texyTypo',%a%ob_get_clean()%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo $textLine%a%
%A%
%s%echo%a%filterContent('texyLine',%a%ob_get_clean()%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo $textBlock%a%
%A%
%s%echo%a%filterContent('texy',%a%ob_get_clean()%a%
%A%
