<?php
%A%source: %a%Bridges/fixtures/filters.default-mode.latte%a%
%A%
%a%echo LR\Filters::escapeHtmlText(($this->filters->texytypo)($textTypo))%a%
%A?%
%a%echo LR\Filters::escapeHtmlText(($this->filters->texyline)($textLine))%a%
%A?%
%a%echo LR\Filters::escapeHtmlText(($this->filters->texy)($textBlock))%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo LR\Filters::escapeHtmlText($textTypo)%a%
%A%
%s%echo%a%filterContent('texytypo',%a%ob_get_clean()%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo $textLine%a%
%A%
%s%echo%a%filterContent('texyline',%a%ob_get_clean()%a%
%A?%
%a%ob_start%A%LatteBlock%a%
%s%echo $textBlock%a%
%A%
%s%echo%a%filterContent('texy',%a%ob_get_clean()%a%
%A%
